---
- hosts: local
  connection: local
  vars:
    bucket_name: "{{ bucket_name }}"
  tasks:
    - name: Delete S3 Bucket
      aws_s3:
        bucket: "{{ bucket_name }}"
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        region: "{{ lookup('env','AWS_DEFAULT_REGION') }}"
        mode: delete
